services:

  ryu:
    build: .
    container_name: ryu
    network_mode: host
    restart: unless-stopped

  containernet:
    image: containernet/containernet
    container_name: containernet
    privileged: true
    pid: host
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./topology.py:/containernet/topology.py
      - ./start.sh:/containernet/start.sh
    depends_on:
      - ryu
    stdin_open: true
    tty: true
    command: bash /containernet/start.sh
